import { SPLogType } from '../enums/SPLogType';
import type { SPLogConfig } from '../models/SPLogConfig';

/**
 * SPLogManager interface defines a method for setting log configurations, allowing for dynamic control over logging behavior based on the provided SPLogConfig or an array of SPLogConfig objects.
 */
interface SPLogManager {
  setLogConfig(configs: SPLogConfig | SPLogConfig[]): void;
}

/**
 * SPLogger interface extends SPLogManager and provides methods for logging messages at different levels (debug, error, info, warning). Each logging method accepts a tag and a message, with the error method also accepting optional error and stack parameters for more detailed logging.
 * This design allows for flexible logging management, enabling developers to easily control the verbosity and content of logs generated by the SDK, which can be crucial for debugging and monitoring in production environments.
 * The SPLoggerImpl class implements the SPLogger interface, providing concrete implementations for each logging method. It includes internal state to manage which log levels are enabled, and it interacts with the native bridge to update log configurations as needed. The logging methods check the corresponding log level before outputting messages to the console, ensuring that only enabled log levels produce output.
 * The SPLogger instance is designed as a singleton, ensuring that there is a single point of control for logging throughout the SDK, and it can be easily imported and used across different modules without needing to manage multiple logger instances.
 */
export interface SPLogger extends SPLogManager {
  /**
   * Debug log
   */
  d(tag: string, msg: string): void;

  /**
   * Error log
   */
  e(
    tag: string,
    msg: string,
    error?: unknown,
    stack?: unknown,
  ): void;

  /**
   * Info log
   */
  i(tag: string, msg: string): void;

  /**
   * Warning log
   */
  w(tag: string, msg: string): void;
}

export class SPLoggerImpl implements SPLogger {
  /** Master switch for internal SDK logs */
  private static readonly internalLogsEnabled: boolean = false;

  /** Log level switches */
  private static debugLogsEnabled: boolean = SPLoggerImpl.internalLogsEnabled;
  private static errorLogsEnabled: boolean = SPLoggerImpl.internalLogsEnabled;
  private static infoLogsEnabled: boolean = SPLoggerImpl.internalLogsEnabled;
  private static warningLogsEnabled: boolean = SPLoggerImpl.internalLogsEnabled;


  setLogConfig(config: SPLogConfig | SPLogConfig[]) {
    const configs = Array.isArray(config) ? config : [config];
    configs.forEach((config) => {
      switch (config.type) {
        case SPLogType.DEBUG:
          SPLoggerImpl.debugLogsEnabled = config.enabled;
          break;
        case SPLogType.ERROR:
          SPLoggerImpl.errorLogsEnabled = config.enabled;
          break;
        case SPLogType.INFO:
          SPLoggerImpl.infoLogsEnabled = config.enabled;
          break;
        case SPLogType.WARNING:
          SPLoggerImpl.warningLogsEnabled = config.enabled;
          break;
        default:
          // eslint-disable-next-line no-console
          console.warn(`Unknown log type: ${config.type}`);
      }
    });
  }

  /**
   * Debug log
   */
  d(tag: string, msg: string): void {
    if (!SPLoggerImpl.debugLogsEnabled) return;
    // eslint-disable-next-line no-console
    console.debug(`[DEBUG][${tag}]: ${msg}`);
  }

  /**
   * Debug log (internal)
   */
  internalD(
    tag: string,
    msg: string,
    error?: unknown,
    stack?: unknown,
  ): void {
    if (!SPLoggerImpl.internalLogsEnabled) return;

    // eslint-disable-next-line no-console
    console.debug(`[DEBUG-ERROR][${tag}]: ${msg}`);

    if (error) {
      // eslint-disable-next-line no-console
      console.debug(`Error:`, error);
    }

    if (stack) {
      // eslint-disable-next-line no-console
      console.debug(`StackTrace:`, stack);
    }
  }

  /**
   * Error log
   */
  e(
    tag: string,
    msg: string,
    error?: unknown,
    stack?: unknown,
  ): void {
    if (!SPLoggerImpl.errorLogsEnabled) return;

    // eslint-disable-next-line no-console
    console.error(`[ERROR][${tag}]: ${msg}`);

    if (error) {
      // eslint-disable-next-line no-console
      console.error(`Error:`, error);
    }

    if (stack) {
      // eslint-disable-next-line no-console
      console.error(`StackTrace:`, stack);
    }
  }

  /**
   * Info log
   */
  i(tag: string, msg: string): void {
    if (!SPLoggerImpl.infoLogsEnabled) return;
    // eslint-disable-next-line no-console
    console.info(`[INFO][${tag}]: ${msg}`);
  }

  /**
   * Warning log
   */
  w(tag: string, msg: string): void {
    if (!SPLoggerImpl.warningLogsEnabled) return;
    // eslint-disable-next-line no-console
    console.warn(`[WARN][${tag}]: ${msg}`);
  }
}

/**
 * Singleton logger instance
 */
export const SPLogger: SPLogger = new SPLoggerImpl();
